Class {
	#name : #CRFModel,
	#superclass : #MooseModel,
	#category : #'Carrefour-Model'
}

{ #category : #accessing }
CRFModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits' #'Famix-Compatibility-Entities' #'FAST-Java-Model' #'FAST-Core-Model')
]

{ #category : #meta }
CRFModel class >> annotation [
	<FMClass: #CRFModel super: #MooseModel>
	<package: #'Carrefour-Model'>
	<generated>
]
