"
Test the binding between FamixJava and Fast

## Create new tests

If youw ant to create new test by updating the famix model.
Remember to use the same end of line for the fast model and the famix model
"
Class {
	#name : #CRFBindingTest,
	#superclass : #CRFTest,
	#category : #'Carrefour-FastAndBindingGenerator-Tests'
}

{ #category : #running }
CRFBindingTest >> testCanLoadFamixAndFastModel [
	"This test will fail if the setup failed --> it will mean that the famix model cannot be load"

	
]
